---
Name: ecommerce_assign_orders
Before: 
  - '#app'
After: 
  - '#coreconfig'
  - '#cmsextensions'
  - '#ecommerce'
---
Sunnysideup\Ecommerce\Model\Order:
  extensions:
    - Sunnysideup\EcommerceAssignOrders\Model\EcommerceAssignOrdersExtension
