---
Name: ecommerce_assign_orders
Before: 'app/*'
After: 'framework/*','cms/*','ecommerce/*'
---
Sunnysideup\Ecommerce\Model\Order:
  extensions:
    - Sunnysideup\EcommerceAssignOrders\Model\EcommerceAssignOrdersExtension
